### ISSUE TITLE
Implement Basic Catching System

### ISSUE THREAD

**Issue by Jac0bDeal** [Jac0bDeal/pikamon#4]
- [x] Add command `catch` (called as `p!ka catch`)
- [x] First call of `catch` with correct spelling awards pokemon to that user (not storing it right now)
- [x] Bot returns a congratulations message with user's tag

**Comment by dlrocker** [comment]
I would like to try the first bullet point as my introduction to go haha

**Comment by Jac0bDeal** [comment]
Have fun!
