### ISSUE TITLE
Add List Pokemon Command

### ISSUE THREAD

**Issue by Jac0bDeal** [Jac0bDeal/pikamon#5]
Add a command that lists a user's pokemon.

- [ ] Add `p!ka list pokemon` command
- [ ] Bot queries for all of user's pokemon
- [ ] Bot returns list of user's pokemon

**Comment by dlrocker** [comment]
Each pokemon should have a unique identifier (UUID) per Pokemon. This way we can trade based on this. We want to be able to say  "I want to trade the 2nd of 5 charmanders I caught for <trade recipients> 3rd squirtle"
