### ISSUE TITLE
Flesh Out Ball Mechanics

### ISSUE THREAD

**Issue by Jac0bDeal** [Jac0bDeal/pikamon#9]
The general idea is that the catching system will allow for different types of balls to be used, each with their own set of pros and cons.

For example, the basic pokeball would require the exact spelling of the name to be correct, whereas other balls could allow for varying degrees of spelling accuracy. Other ideas so far have been for a ball that gives advantage based on speed of reaction, a ball that just requires the correct type(s), etc.

This issue is to document ideas for ball mechanics, and subsequent issues will be opened to implement them.

**Comment by dlrocker** [comment]
List of pokeball types
- https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9_Ball

**Comment by Jac0bDeal** [comment]
We decided that balls add too much complexity and the bot is best doing what pokecord did with catching purely by name. Perhaps we could implement a cooldown to give more chance to slower typers.
